THORSANVIL_ROOT             = $(realpath ../../)
COVERAGE_REQUIRED			= 70

TARGET                      = ThorsSocket.slib

LDLIBS_EXTERN_BUILD			= $(crypto_ROOT_LIB) $(ThorSerialize_ROOT_LIB)

include $(THORSANVIL_ROOT)/build/tools/Makefile
